#!/bin/bash
# codex-review.sh - Git commit 전 Codex를 통한 코드 리뷰
# PreToolUse Hook (Bash matcher)에서 실행

set -e

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
REVIEWS_DIR="$PROJECT_DIR/.reviews"

# 1. 환경변수로 리뷰 스킵 가능
if [ "${SKIP_CODEX_REVIEW:-}" = "1" ]; then
    echo '{"decision":"approve"}'
    exit 0
fi

# 2. git commit 명령인지 확인
TOOL_INPUT="${CLAUDE_TOOL_INPUT:-}"
if [ -z "$TOOL_INPUT" ]; then
    echo '{"decision":"approve"}'
    exit 0
fi

# jq로 command 추출
COMMAND=$(echo "$TOOL_INPUT" | jq -r '.command // empty' 2>/dev/null)
if [ -z "$COMMAND" ]; then
    echo '{"decision":"approve"}'
    exit 0
fi

# git commit 명령이 아니면 통과
if ! echo "$COMMAND" | grep -qE '^git commit'; then
    echo '{"decision":"approve"}'
    exit 0
fi

# 3. Codex CLI 설치 확인
if ! command -v codex &> /dev/null; then
    cat << 'EOF' >&2

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  Codex CLI not installed - skipping code review
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Install with: npm i -g @openai/codex

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
    echo '{"decision":"approve"}'
    exit 0
fi

# 4. Staged 파일 수집
cd "$PROJECT_DIR"
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null)

if [ -z "$STAGED_FILES" ]; then
    echo '{"decision":"approve"}'
    exit 0
fi

# 5. 리뷰할 파일 필터링 (코드 파일만)
CODE_FILES=$(echo "$STAGED_FILES" | grep -E '\.(py|js|ts|tsx|jsx|sh|json|yaml|yml|go|rs|java|c|cpp|h|hpp)$' || true)

if [ -z "$CODE_FILES" ]; then
    echo '{"decision":"approve"}'
    exit 0
fi

# 6. 리뷰 디렉토리 생성
TODAY=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%H%M%S)
SHORT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "new")
REVIEW_SUBDIR="$REVIEWS_DIR/$TODAY"
mkdir -p "$REVIEW_SUBDIR"

REVIEW_FILE="$REVIEW_SUBDIR/${SHORT_HASH}_${TIMESTAMP}.md"

# 7. Diff 수집
DIFF_CONTENT=$(git diff --cached 2>/dev/null)

# 8. 프롬프트 구성
PROMPT=$(cat << 'PROMPT_EOF'
You are a code reviewer. Analyze the following staged git changes.

## Review Focus:
1. **Code Quality**: Logic errors, bugs, edge cases
2. **Architecture**: Design patterns, dependencies, structure
3. **Best Practices**: Naming, documentation, error handling
4. **Security**: Potential vulnerabilities, secrets exposure
5. **Tests**: If test files are present, check coverage

## Output Format (Markdown):

### Summary
- **Assessment**: PASS | NEEDS_ATTENTION
- **Description**: Brief overall assessment

### Issues Found
| Severity | File | Line | Issue | Suggestion |
|----------|------|------|-------|------------|
| HIGH/MEDIUM/LOW | filename | line# | description | fix suggestion |

(If no issues, write "No significant issues found.")

### Recommendations
- List improvement suggestions (or "None" if code looks good)

PROMPT_EOF
)

# 파일 목록 및 diff 추가
FULL_PROMPT="$PROMPT

## Staged Files:
$CODE_FILES

## Changes (git diff --cached):
\`\`\`diff
$DIFF_CONTENT
\`\`\`
"

# 9. 리뷰 시작 알림
cat << EOF >&2

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔍 Codex Code Review in progress...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Reviewing files:
$(echo "$CODE_FILES" | sed 's/^/  - /')

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF

# 10. Codex 실행 (타임아웃 180초)
CODEX_OUTPUT=""
CODEX_EXIT_CODE=0

# quiet 모드로 실행, stdin으로 프롬프트 전달
CODEX_OUTPUT=$(echo "$FULL_PROMPT" | timeout 180 codex -q - 2>/dev/null) || CODEX_EXIT_CODE=$?

# 11. Codex 실패 처리
if [ $CODEX_EXIT_CODE -ne 0 ] || [ -z "$CODEX_OUTPUT" ]; then
    cat > "$REVIEW_FILE" << EOF
# Code Review Report (Failed)

- **Date**: $(date +"%Y-%m-%d %H:%M:%S")
- **Status**: CODEX_FAILED
- **Exit Code**: $CODEX_EXIT_CODE

## Staged Files
$(echo "$CODE_FILES" | sed 's/^/- /')

---
*Review failed. Proceeding with commit.*
EOF

    cat << EOF >&2

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  Codex review failed (exit code: $CODEX_EXIT_CODE)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Proceeding with commit anyway.
Report saved: $REVIEW_FILE

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF

    echo '{"decision":"approve"}'
    exit 0
fi

# 12. 리뷰 결과 저장
cat > "$REVIEW_FILE" << EOF
# Code Review Report

- **Date**: $(date +"%Y-%m-%d %H:%M:%S")
- **Commit**: $SHORT_HASH
- **Reviewer**: OpenAI Codex

## Staged Files
$(echo "$CODE_FILES" | sed 's/^/- /')

---

$CODEX_OUTPUT

---
*Generated by codex-review.sh*
EOF

# 13. 결과 출력 (경고만, 차단 없음)
if echo "$CODEX_OUTPUT" | grep -qiE 'NEEDS_ATTENTION'; then
    cat << EOF >&2

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  Code Review: NEEDS ATTENTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Review report: $REVIEW_FILE

Some issues were found. Please review after commit.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
else
    cat << EOF >&2

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ Code Review: PASSED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Review report: $REVIEW_FILE

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
fi

# 14. 항상 approve (경고만, 차단 없음)
echo '{"decision":"approve"}'
exit 0
